### ISSUE TITLE
feed name

### ISSUE THREAD

**Issue by whoizit** [rossnomann/telefeed#4]
I have a lot of subscriptions and it’s not always possible to determine which feed this message is from

**Comment by rossnomann** [comment]
Added `include_feed_title` option to config. `false` by default.
Looks like this:
![image](https://user-images.githubusercontent.com/28867223/74891192-bdf3d300-539f-11ea-8b5a-b94958358e79.png)

**Comment by whoizit** [comment]
thanks a lot
