### ISSUE TITLE
connection error: Connection reset by peer (os error 104)

### ISSUE THREAD

**Issue by whoizit** [rossnomann/telefeed#5]
I think the sites are blocked due to frequent requests. I have a lot of this errors from different sites. We need a mechanism that changes the frequency of polling sites. 

Maybe this can be done dynamically, if such an error occurs, increase the timeout between requests to the site. I'm subscribed to many feeds on the same site. Please keep in mind that there can be several feeds on the same site and the site may be blocked due to frequent requests. For example, I have a lot of youtube feeds.

These errors occur even on single feed sites.

```
ERROR telefeed::syndicate] Failed to get entries for feed https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_NOVOSTI: http request error: error sending request for url (https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_NOVOSTI): connection error: Connection reset by peer (os error
104)
```

**Comment by rossnomann** [comment]
Released 0.3.0 with request_timeout option support.
Previously there was a 60 seconds timeout between each request, so it's reasonable that you get such errors.
Now it is 20 minutes by default for each feed. You can override it globally and/or for a specific feed.
If you will have issues with youtube feeds after upgrade, try to set different request_timeout for each feed.
